# Generated by Django 6.0.3 on 2026-03-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En utilisation'), ('maintenance', 'En maintenance')], max_length=20)),
            ],
        ),
    ]
