<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-03-28 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Équipement', 'verbose_name_plural': 'Équipements'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, help_text="Date d'acquisition de l'équipement", verbose_name="Date d'achat"),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En utilisation'), ('maintenance', 'En maintenance')], default='available', max_length=20),
        ),
    ]
=======
# Generated by Django 6.0.3 on 2026-03-28 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Équipement', 'verbose_name_plural': 'Équipements'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, help_text="Date d'acquisition de l'équipement", verbose_name="Date d'achat"),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En utilisation'), ('maintenance', 'En maintenance')], default='available', max_length=20),
        ),
    ]
>>>>>>> 5bd48501490524661776bca42704bc3a758b0c75
