name: Deploy Django to PythonAnywhere

on:
  push:
    branches:
      - main  # Vérifiez si votre branche principale s'appelle 'main' ou 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Adaptez à votre version sur PythonAnywhere

      - name: Re-Deploy on PythonAnywhere
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.0
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          api_token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          domain_name: ${{ secrets.PYTHONANYWHERE_WEBAPP_DOMAIN }}
