name: Deploy Django to PythonAnywhere

on:
  push:
    branches:
      - main  # Vérifie si ta branche principale s'appelle bien 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer ton code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Python (version identique à celle configurée sur PythonAnywhere)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Adapte à ta version sur PythonAnywhere

  
      # 3. Déployer sur PythonAnywhere via l’action dédiée
      - name: Re-Deploy on PythonAnywhere
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.0
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          api_token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          domain_name: ${{ secrets.PYTHONANYWHERE_WEBAPP_DOMAIN }}
